apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vegetable-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://psy-ship-it.github.io/Vegetable-order-app
    chart: veg-app
    targetRevision: "*" 
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: sahil-ns 

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

